config/routes.rb
SiteEtu::Application.routes.draw do
  devise_for :users

  # Ressources
  resource :activity, only: :show
  resource :cas, only: [:new, :destroy]

  resources :votes, only: [:create, :destroy]
  resources :users, only: [:index, :edit, :show, :update]
  resources :polls, :timesheets, :quotes
  resources :roles, except: [:new, :create]
  resources :courses do
    resources :comments, only: [:create, :destroy]
  end
  resources :assos, :classifieds, :carpools, :events, :projects,
            :news, :wikis, :annals do
    resources :comments, only: [:create, :destroy]
    resources :documents, only: [:create, :destroy]
  end
  resources :assos, :events, only: [ ] do
    # 'only: [ ]' because we don't want duplicated default routes (#index, #show, etc.)
    member do
      post :join
      post :disjoin
    end
  end

  root to: 'home#index'

  # Routes spéciales
  get 'about' => 'home#about', via: :get
  get 'rules' => 'home#rules', via: :get
  get 'deploy' => 'application#deploy', via: :get
  get 'preview' => 'application#preview' # Prévisualisation Markdown
  get '*path' => 'application#render_not_found'
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  TAGS = %w(all quote tip joke)

  paginates_per 30
  has_paper_trail

  validates_presence_of :content
  validates :tag, inclusion: {in: Quote::TAGS}

  def to_s
    content
  end
end

app/controllers/quotes_controller.rb
# encoding: utf-8
class QuotesController < ApplicationController
  load_and_authorize_resource

  def index
    respond_to do |format|
      format.html
      format.json { render json: @quotes }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @quote }
    end
  end

  def new
    render_new quotes_path
  end

  def edit
    render_edit @quote
  end

  def create
    if @quote.save
      redirect_to(@quote, notice: t('c.created'))
    else
      render_edit @quote
    end
  end

  def update
    if @quote.update_attributes(params[:quote])
      redirect_to(@quote, notice: t('c.updated'))
    else
      render_edit @quote
    end
  end

  def destroy
    @quote.destroy

    redirect_to(quotes_url)
  end
end

app/views/quotes/_form.html.haml
= form_for(@quote) do |f|
  = f.error_messages

  %ul.fields
    %li.field
      = f.label :content, t('quotes.content')
      = f.text_field :content

    %li.field
      = f.label :author, t('quotes.by')
      = f.text_field :author

    %li.field
      = f.label :tag, t('quotes.type')
      = f.select :tag, Quote::TAGS

    %li.actions
      = f.submit t('common.submit')

app/views/quotes/index.html.haml
%section.content
  = title t('quotes.list')

  - @quotes.each do |quote|
    %blockquote
      = link_to quote.content, quote

  - if can? :create, Quote
    %ul.actions
      %li= link_to t('common.add'), new_quote_path

app/views/quotes/show.html.haml
%section.content
  = title t('quotes.list')

  %blockquote= link_to @quote.content, @quote

  %p
    = t('quotes.by')
    #{@quote.author} (#{@quote.tag})

  = render 'layouts/show_actions', {resource: @quote}