config/routes.rb
SiteEtu::Application.routes.draw do
  devise_for :users

  # Ressources
  resource :activity, only: :show
  resource :cas, only: [:new, :destroy]

  resources :votes, only: [:create, :destroy]
  resources :users, only: [:index, :edit, :show, :update]
  resources :polls, :timesheets, :quotes
  resources :roles, except: [:new, :create]
  resources :courses do
    resources :comments, only: [:create, :destroy]
  end
  resources :assos, :classifieds, :carpools, :events, :projects,
            :news, :wikis, :annals do
    resources :comments, only: [:create, :destroy]
    resources :documents, only: [:create, :destroy]
  end
  resources :assos, :events, only: [ ] do
    # 'only: [ ]' because we don't want duplicated default routes (#index, #show, etc.)
    member do
      post :join
      post :disjoin
    end
  end

  root to: 'home#index'

  # Routes spéciales
  get 'about' => 'home#about', via: :get
  get 'rules' => 'home#rules', via: :get
  get 'deploy' => 'application#deploy', via: :get
  get 'preview' => 'application#preview' # Prévisualisation Markdown
  get '*path' => 'application#render_not_found'
end

app/models/carpool.rb
# encoding: utf-8

class Carpool < ActiveRecord::Base
  has_paper_trail
  paginates_per 30
  include Extensions::Searchable
  searchable_attributes :description, :departure, :arrival

  validates_presence_of :description, :departure, :arrival, :date, :user


  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :documents, as: :documentable, dependent: :destroy

  def to_s
    "#{departure} → #{arrival} (#{I18n.l(date, format: :short)})"
  end
end

app/controllers/carpools_controller.rb
# encoding: utf-8
class CarpoolsController < ApplicationController
  load_and_authorize_resource

  before_filter :search_and_paginate, only: :index
  before_filter :decorate, only: [:index, :show]

  def index
    @drivers = @carpools.select { |car| car.is_driver }
    @not_drivers = @carpools.select { |car| !car.is_driver }

    respond_to do |format|
      format.html
      format.json { render json: @carpools }
    end
  end

  def show
    @comments = @carpool.comments
    @documents = @carpool.documents

    if @carpool.is_driver
      @driver_or_passenger =  I18n.t('carpools.driver')
    else
      @driver_or_passenger = I18n.t('carpools.passenger')
    end

    respond_to do |format|
      format.html
      format.json { render json: @carpool }
    end
  end

  def new
    render_new carpools_path
  end

  def edit
    render_edit @carpool
  end

  def create
    @carpool.user = current_user

    if @carpool.save
      redirect_to(@carpool, notice: t('c.created'))
    else
      render_edit @carpool
    end
  end

  def update
    if @carpool.update_attributes(params[:carpool])
      redirect_to(@carpool, notice: t('c.updated'))
    else
      render_edit @carpool
    end
  end

  def destroy
    @carpool.destroy

    redirect_to(carpools_url)
  end
end

app/views/carpools/_form.html.haml
= form_for(@carpool) do |f|
  = f.error_messages

  %ul.fields
    %li.field
      = f.label :description, t('carpools.description')
      = f.text_area :description, class: 'rich-content'

    %li.field
      = f.label :departure, t('carpools.departure')
      = f.text_field :departure

    %li.field
      = f.label :arrival, t('carpools.arrival')
      = f.text_field :arrival

    %li.field
      = f.label :date, t('carpools.date')
      = f.datetime_select :date

    %li.field
      = f.label :is_driver, t('carpools.is_driver')
      = f.check_box :is_driver

    %li.actions
      = f.submit t('common.submit')

app/views/carpools/index.html.haml
%section.content
  = title t('carpools.list')

  = search_form(carpools_path)

  %h2= t('carpools.drivers')
  = links_to_objects @drivers, true

  %h2= t('carpools.passengers')
  = links_to_objects @not_drivers, true

  = paginate @carpools unless @carpools.empty?

  - if can? :create, Carpool
    %ul.actions
      %li= link_to t('common.add'), new_carpool_path

app/views/carpools/show.html.haml
%section.content
  = title("#{@driver_or_passenger} : #{@carpool.to_s}")

  %p
    %strong= t('carpools.user')
    = @carpool.user.link

  = dl(@carpool, %w(user))

  = @carpool.description

  = render 'layouts/show_actions', resource: @carpool

= render 'documents/list_and_add', {documentable: @carpool, documents: @documents}
= render 'comments/list_and_add', {commentable: @carpool, comments: @comments}