config/routes.rb
SiteEtu::Application.routes.draw do
  devise_for :users

  # Ressources
  resource :activity, only: :show
  resource :cas, only: [:new, :destroy]

  resources :votes, only: [:create, :destroy]
  resources :users, only: [:index, :edit, :show, :update]
  resources :polls, :timesheets, :quotes
  resources :roles, except: [:new, :create]
  resources :courses do
    resources :comments, only: [:create, :destroy]
  end
  resources :assos, :classifieds, :carpools, :events, :projects,
            :news, :wikis, :annals do
    resources :comments, only: [:create, :destroy]
    resources :documents, only: [:create, :destroy]
  end
  resources :assos, :events, only: [ ] do
    # 'only: [ ]' because we don't want duplicated default routes (#index, #show, etc.)
    member do
      post :join
      post :disjoin
    end
  end

  root to: 'home#index'

  # Routes spéciales
  get 'about' => 'home#about', via: :get
  get 'rules' => 'home#rules', via: :get
  get 'deploy' => 'application#deploy', via: :get
  get 'preview' => 'application#preview' # Prévisualisation Markdown
  get '*path' => 'application#render_not_found'
end

app/models/project.rb
class Project < ActiveRecord::Base
  paginates_per 20
  has_paper_trail
  include Extensions::Searchable
  searchable_attributes :name, :description

  validates_presence_of :name
  validates_uniqueness_of :name
  validate :at_least_one_user

  has_many :comments, as: :commentable, dependent: :destroy
  has_many :documents, as: :documentable, dependent: :destroy

  has_many :projects_user, dependent: :destroy
  has_many :users, through: :projects_user, uniq: true

  # There should be at least one user in the project
  def at_least_one_user
    if users.size < 1
      errors.add(:users, I18n.t('model.project.at_least_one_user'))
    end
  end

  def to_s
    res = name
    res += " : #{description.truncate(60)}" unless description.blank?
    res
  end
end

app/controllers/projects_controller.rb
# encoding: utf-8

class ProjectsController < ApplicationController
  load_and_authorize_resource

  before_filter :search_and_paginate, only: :index
  before_filter :set_first_users, only: [:new, :edit]
  before_filter :add_users, only: [:create, :update]

  def index
    respond_to do |format|
      format.html
      format.json { render json: @projects }
    end
  end

  def show
    @comments = @project.comments
    @documents = @project.documents

    respond_to do |format|
      format.html
      format.json { render json: @project }
    end
  end

  def new
    render_new projects_path
  end

  def edit
    render_edit @project
  end

  def create
    @project.users << current_user unless @project.users.include?(current_user)

    if @project.save
      redirect_to(@project, notice: t('c.created'))
    else
      render_edit @project
    end
  end

  def update
    if @project.update_attributes(params[:project])
      redirect_to(@project, notice: t('c.updated'))
    else
      render_edit @project
    end
  end

  def destroy
    @project.destroy

    redirect_to(projects_url)
  end

  private
  def add_users
    @project.users = params[:users] ? User.find(params[:users]) : []
  end
end

app/views/projects/_form.html.haml
= form_for(@project) do |f|
  = f.error_messages

  %ul.fields
    %li.field
      = f.label :name, t('projects.name')
      = f.text_field :name

    %li.field
      = f.label :description, t('projects.description')
      = f.text_area :description, class: 'rich-content'

    %li.field
      = label_tag :users, t('timesheets.users')
      = select_tag :users, select_objects(@first_users, @project.users, false), |
        :multiple => true, :class => 'users-chosen'                            |

    %li.actions
      = f.submit t('common.submit')

app/views/projects/index.html.haml
%section.content
  = title t('projects.list')

  = search_form(projects_path)

  = links_to_objects(@projects, true)

  - if can? :create, Project
    %ul.actions
      %li= link_to t('common.add'), new_project_path

app/views/projects/show.html.haml
%section.content
  = title(@project.to_s)

  %p= not_empty_inline(t('projects.users'), links_to_users(@project.users))

  = md @project.description

  = render 'layouts/show_actions', resource: @project

= render 'documents/list_and_add', {documentable: @project, documents: @documents}
= render 'comments/list_and_add', {commentable: @project, comments: @comments}