config/routes.rb
SiteEtu::Application.routes.draw do
  devise_for :users

  # Ressources
  resource :activity, only: :show
  resource :cas, only: [:new, :destroy]

  resources :votes, only: [:create, :destroy]
  resources :users, only: [:index, :edit, :show, :update]
  resources :polls, :timesheets, :quotes
  resources :roles, except: [:new, :create]
  resources :courses do
    resources :comments, only: [:create, :destroy]
  end
  resources :assos, :classifieds, :carpools, :events, :projects,
            :news, :wikis, :annals do
    resources :comments, only: [:create, :destroy]
    resources :documents, only: [:create, :destroy]
  end
  resources :assos, :events, only: [ ] do
    # 'only: [ ]' because we don't want duplicated default routes (#index, #show, etc.)
    member do
      post :join
      post :disjoin
    end
  end

  root to: 'home#index'

  # Routes spéciales
  get 'about' => 'home#about', via: :get
  get 'rules' => 'home#rules', via: :get
  get 'deploy' => 'application#deploy', via: :get
  get 'preview' => 'application#preview' # Prévisualisation Markdown
  get '*path' => 'application#render_not_found'
end

app/models/classified.rb
# encoding: utf-8

class Classified < ActiveRecord::Base
  paginates_per 50
  has_paper_trail
  include Extensions::Searchable
  searchable_attributes :title, :description, :price, :location

  validates_presence_of :title, :description

  belongs_to :user
  has_many :documents, as: :documentable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  def to_s
    "#{price}€ : #{title}"
  end
end

app/controllers/classifieds_controller.rb
# encoding: utf-8
class ClassifiedsController < ApplicationController
  load_and_authorize_resource

  before_filter :search_and_paginate, only: :index

  def index
    respond_to do |format|
      format.html
      format.json { render json: @classifieds }
      format.rss { render layout: false }
    end
  end

  def show
    @comments = @classified.comments
    @documents = @classified.documents

    respond_to do |format|
      format.html
      format.json { render json: @classified }
    end
  end

  def new
    render_new classifieds_path
  end

  def edit
    render_edit @classified
  end

  def create
    @classified.user = current_user

    if @classified.save
      redirect_to(@classified, notice: t('c.created'))
    else
      render_edit @classified
    end
  end

  def update
    if @classified.update_attributes(params[:classified])
      redirect_to(@classified, notice: t('c.updated'))
    else
      render_edit @classified
    end
  end

  def destroy
    @classified.destroy

    redirect_to(classifieds_url)
  end
end

app/views/classifieds/_form.html.haml
= form_for(@classified) do |f|
  = f.error_messages

  %ul.fields
    %li.field
      = f.label :title, t('classifieds.title')
      = f.text_field :title

    %li.field
      = f.label :description, t('classifieds.description')
      = f.text_area :description, class: 'rich-content'

    %li.field
      = f.label :price, t('classifieds.price')
      = f.text_field :price

    %li.field
      = f.label :location, t('classifieds.location')
      = f.text_field :location

    %li.actions
      = f.submit t('common.submit')

app/views/classifieds/index.html.haml
%section.content
  = title t('classifieds.list')

  = search_form(classifieds_path)

  = links_to_objects @classifieds, true

  = paginate @classifieds unless @classifieds.empty?

  - if can? :create, Classified
    %ul.actions
      %li= link_to t('common.add'), new_classified_path

app/views/classifieds/show.html.haml
%section.content
  = title(@classified.to_s)

  = dl_inline @classified, %w(price location user)

  = md @classified.description

  = render 'layouts/show_actions', resource: @classified

= render 'documents/list_and_add', {documentable: @classified, documents: @documents}
= render 'comments/list_and_add', {commentable: @classified, comments: @comments}